# Generated by Django 3.2 on 2022-01-06 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication_app', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
